### ISSUE TITLE
Inconsistency between input and output length

### ISSUE THREAD

**Issue by tan90xx** [chaufanglin/Normal2Whisper#1]
Hello! Thank you for your great work! I have two questions:
1) Why there is inconsistency between input and output length? 
    maybe it's because `pw.synthesize`
2) Can I use output[  :len(input)] to fix this issue?

**Comment by chaufanglin** [comment]
Hi, thanks for showing interest in this work.

1. Yes. I think this inconsistency is caused by the WORLD vocoder. If you try decomposing a speech signal using WORLD vocoder and reconstructing the components to a speech signal, the inconsistency still happens.

2. You could use this `output[:len(input)]`, you can check whether the part you discard is almost all zero.

**Comment by tan90xx** [comment]
Thanks a lot~
